/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables;


import com.jooq.domain.Indexes;
import com.jooq.domain.Keys;
import com.jooq.domain.Xbkj;
import com.jooq.domain.tables.records.FdReportEbusinessAddressRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 电商数据报告地址
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdReportEbusinessAddress extends TableImpl<FdReportEbusinessAddressRecord> {

    private static final long serialVersionUID = 1633669567;

    /**
     * The reference instance of <code>xbkj.fd_report_ebusiness_address</code>
     */
    public static final FdReportEbusinessAddress FD_REPORT_EBUSINESS_ADDRESS = new FdReportEbusinessAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FdReportEbusinessAddressRecord> getRecordType() {
        return FdReportEbusinessAddressRecord.class;
    }

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.id</code>.
     */
    public final TableField<FdReportEbusinessAddressRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.report_ebusiness_id</code>.
     */
    public final TableField<FdReportEbusinessAddressRecord, Long> REPORT_EBUSINESS_ID = createField("report_ebusiness_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.name</code>. 收货人姓名
     */
    public final TableField<FdReportEbusinessAddressRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(128), this, "收货人姓名");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.phone</code>. 收货人电话
     */
    public final TableField<FdReportEbusinessAddressRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(128), this, "收货人电话");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.address</code>. 地址
     */
    public final TableField<FdReportEbusinessAddressRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(128), this, "地址");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.is_default</code>. 是否默认地址
     */
    public final TableField<FdReportEbusinessAddressRecord, String> IS_DEFAULT = createField("is_default", org.jooq.impl.SQLDataType.VARCHAR(64), this, "是否默认地址");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.create_at</code>. 创建时间
     */
    public final TableField<FdReportEbusinessAddressRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.update_at</code>. 更新时间
     */
    public final TableField<FdReportEbusinessAddressRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.del_flag</code>. 删除标志
     */
    public final TableField<FdReportEbusinessAddressRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "删除标志");

    /**
     * The column <code>xbkj.fd_report_ebusiness_address.version</code>.
     */
    public final TableField<FdReportEbusinessAddressRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>xbkj.fd_report_ebusiness_address</code> table reference
     */
    public FdReportEbusinessAddress() {
        this(DSL.name("fd_report_ebusiness_address"), null);
    }

    /**
     * Create an aliased <code>xbkj.fd_report_ebusiness_address</code> table reference
     */
    public FdReportEbusinessAddress(String alias) {
        this(DSL.name(alias), FD_REPORT_EBUSINESS_ADDRESS);
    }

    /**
     * Create an aliased <code>xbkj.fd_report_ebusiness_address</code> table reference
     */
    public FdReportEbusinessAddress(Name alias) {
        this(alias, FD_REPORT_EBUSINESS_ADDRESS);
    }

    private FdReportEbusinessAddress(Name alias, Table<FdReportEbusinessAddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private FdReportEbusinessAddress(Name alias, Table<FdReportEbusinessAddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "电商数据报告地址");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Xbkj.XBKJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FD_REPORT_EBUSINESS_ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FdReportEbusinessAddressRecord, Long> getIdentity() {
        return Keys.IDENTITY_FD_REPORT_EBUSINESS_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FdReportEbusinessAddressRecord> getPrimaryKey() {
        return Keys.KEY_FD_REPORT_EBUSINESS_ADDRESS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FdReportEbusinessAddressRecord>> getKeys() {
        return Arrays.<UniqueKey<FdReportEbusinessAddressRecord>>asList(Keys.KEY_FD_REPORT_EBUSINESS_ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessAddress as(String alias) {
        return new FdReportEbusinessAddress(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessAddress as(Name alias) {
        return new FdReportEbusinessAddress(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FdReportEbusinessAddress rename(String name) {
        return new FdReportEbusinessAddress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FdReportEbusinessAddress rename(Name name) {
        return new FdReportEbusinessAddress(name, null);
    }
}
