/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables;


import com.jooq.domain.Indexes;
import com.jooq.domain.Keys;
import com.jooq.domain.Xbkj;
import com.jooq.domain.enums.UcMemberRequestLoanStatus;
import com.jooq.domain.enums.UcMemberRequestLoanType;
import com.jooq.domain.tables.records.UcMemberRequestLoanRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 会员申请额度或者激活表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcMemberRequestLoan extends TableImpl<UcMemberRequestLoanRecord> {

    private static final long serialVersionUID = -1985589097;

    /**
     * The reference instance of <code>xbkj.uc_member_request_loan</code>
     */
    public static final UcMemberRequestLoan UC_MEMBER_REQUEST_LOAN = new UcMemberRequestLoan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UcMemberRequestLoanRecord> getRecordType() {
        return UcMemberRequestLoanRecord.class;
    }

    /**
     * The column <code>xbkj.uc_member_request_loan.id</code>.
     */
    public final TableField<UcMemberRequestLoanRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>xbkj.uc_member_request_loan.member_id</code>. 会员ID
     */
    public final TableField<UcMemberRequestLoanRecord, Long> MEMBER_ID = createField("member_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "会员ID");

    /**
     * The column <code>xbkj.uc_member_request_loan.type</code>. 申请，提额
     */
    public final TableField<UcMemberRequestLoanRecord, UcMemberRequestLoanType> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(5).nullable(false).defaultValue(org.jooq.impl.DSL.inline("apply", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(com.jooq.domain.enums.UcMemberRequestLoanType.class), this, "申请，提额");

    /**
     * The column <code>xbkj.uc_member_request_loan.status</code>. 处理，系统计算，未审核，已审核，已拒绝
     */
    public final TableField<UcMemberRequestLoanRecord, UcMemberRequestLoanStatus> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(9).nullable(false).defaultValue(org.jooq.impl.DSL.inline("process", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(com.jooq.domain.enums.UcMemberRequestLoanStatus.class), this, "处理，系统计算，未审核，已审核，已拒绝");

    /**
     * The column <code>xbkj.uc_member_request_loan.tongdun</code>. 备注
     */
    public final TableField<UcMemberRequestLoanRecord, String> TONGDUN = createField("tongdun", org.jooq.impl.SQLDataType.CLOB, this, "备注");

    /**
     * The column <code>xbkj.uc_member_request_loan.remarks</code>. 备注
     */
    public final TableField<UcMemberRequestLoanRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR(255), this, "备注");

    /**
     * The column <code>xbkj.uc_member_request_loan.create_at</code>. 创建时间
     */
    public final TableField<UcMemberRequestLoanRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>xbkj.uc_member_request_loan.update_at</code>. 更新时间
     */
    public final TableField<UcMemberRequestLoanRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>xbkj.uc_member_request_loan.del_flag</code>. 删除标志
     */
    public final TableField<UcMemberRequestLoanRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "删除标志");

    /**
     * The column <code>xbkj.uc_member_request_loan.version</code>.
     */
    public final TableField<UcMemberRequestLoanRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>xbkj.uc_member_request_loan.admittance</code>. 准入条件json
     */
    public final TableField<UcMemberRequestLoanRecord, String> ADMITTANCE = createField("admittance", org.jooq.impl.SQLDataType.CLOB, this, "准入条件json");

    /**
     * The column <code>xbkj.uc_member_request_loan.warning</code>. 预计条件json
     */
    public final TableField<UcMemberRequestLoanRecord, String> WARNING = createField("warning", org.jooq.impl.SQLDataType.CLOB, this, "预计条件json");

    /**
     * The column <code>xbkj.uc_member_request_loan.score</code>. 本次评分卡计算结果
     */
    public final TableField<UcMemberRequestLoanRecord, Double> SCORE = createField("score", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DOUBLE)), this, "本次评分卡计算结果");

    /**
     * The column <code>xbkj.uc_member_request_loan.credit_amount</code>. 本次授信额度
     */
    public final TableField<UcMemberRequestLoanRecord, BigDecimal> CREDIT_AMOUNT = createField("credit_amount", org.jooq.impl.SQLDataType.DECIMAL(20, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "本次授信额度");

    /**
     * The column <code>xbkj.uc_member_request_loan.audit_credit_amount</code>. 审核授信额度
     */
    public final TableField<UcMemberRequestLoanRecord, BigDecimal> AUDIT_CREDIT_AMOUNT = createField("audit_credit_amount", org.jooq.impl.SQLDataType.DECIMAL(20, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "审核授信额度");

    /**
     * The column <code>xbkj.uc_member_request_loan.agin_limit_flag</code>. 是否重复提额
     */
    public final TableField<UcMemberRequestLoanRecord, Boolean> AGIN_LIMIT_FLAG = createField("agin_limit_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "是否重复提额");

    /**
     * Create a <code>xbkj.uc_member_request_loan</code> table reference
     */
    public UcMemberRequestLoan() {
        this(DSL.name("uc_member_request_loan"), null);
    }

    /**
     * Create an aliased <code>xbkj.uc_member_request_loan</code> table reference
     */
    public UcMemberRequestLoan(String alias) {
        this(DSL.name(alias), UC_MEMBER_REQUEST_LOAN);
    }

    /**
     * Create an aliased <code>xbkj.uc_member_request_loan</code> table reference
     */
    public UcMemberRequestLoan(Name alias) {
        this(alias, UC_MEMBER_REQUEST_LOAN);
    }

    private UcMemberRequestLoan(Name alias, Table<UcMemberRequestLoanRecord> aliased) {
        this(alias, aliased, null);
    }

    private UcMemberRequestLoan(Name alias, Table<UcMemberRequestLoanRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "会员申请额度或者激活表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Xbkj.XBKJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UC_MEMBER_REQUEST_LOAN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UcMemberRequestLoanRecord, Long> getIdentity() {
        return Keys.IDENTITY_UC_MEMBER_REQUEST_LOAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UcMemberRequestLoanRecord> getPrimaryKey() {
        return Keys.KEY_UC_MEMBER_REQUEST_LOAN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UcMemberRequestLoanRecord>> getKeys() {
        return Arrays.<UniqueKey<UcMemberRequestLoanRecord>>asList(Keys.KEY_UC_MEMBER_REQUEST_LOAN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcMemberRequestLoan as(String alias) {
        return new UcMemberRequestLoan(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcMemberRequestLoan as(Name alias) {
        return new UcMemberRequestLoan(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UcMemberRequestLoan rename(String name) {
        return new UcMemberRequestLoan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UcMemberRequestLoan rename(Name name) {
        return new UcMemberRequestLoan(name, null);
    }
}
