/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables;


import com.jooq.domain.Indexes;
import com.jooq.domain.Keys;
import com.jooq.domain.Xbkj;
import com.jooq.domain.enums.UcYeepayRequestIdType;
import com.jooq.domain.tables.records.UcYeepayRequestIdRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcYeepayRequestId extends TableImpl<UcYeepayRequestIdRecord> {

    private static final long serialVersionUID = 621290778;

    /**
     * The reference instance of <code>xbkj.uc_yeepay_request_id</code>
     */
    public static final UcYeepayRequestId UC_YEEPAY_REQUEST_ID = new UcYeepayRequestId();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UcYeepayRequestIdRecord> getRecordType() {
        return UcYeepayRequestIdRecord.class;
    }

    /**
     * The column <code>xbkj.uc_yeepay_request_id.id</code>.
     */
    public final TableField<UcYeepayRequestIdRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.source_id</code>. 机构id，门店id
     */
    public final TableField<UcYeepayRequestIdRecord, Long> SOURCE_ID = createField("source_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "机构id，门店id");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.request_id</code>. 机构或门店易宝注册请求号
     */
    public final TableField<UcYeepayRequestIdRecord, Long> REQUEST_ID = createField("request_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "机构或门店易宝注册请求号");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.customernumber_id</code>. 主账户的商户编号
     */
    public final TableField<UcYeepayRequestIdRecord, Long> CUSTOMERNUMBER_ID = createField("customernumber_id", org.jooq.impl.SQLDataType.BIGINT, this, "主账户的商户编号");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.yeepay_id</code>. 子账户商户编号
     */
    public final TableField<UcYeepayRequestIdRecord, Long> YEEPAY_ID = createField("yeepay_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "子账户商户编号");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.type</code>. 机构，门店
     */
    public final TableField<UcYeepayRequestIdRecord, UcYeepayRequestIdType> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(5).nullable(false).asEnumDataType(com.jooq.domain.enums.UcYeepayRequestIdType.class), this, "机构，门店");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.create_at</code>. 创建时间
     */
    public final TableField<UcYeepayRequestIdRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.update_at</code>. 更新时间
     */
    public final TableField<UcYeepayRequestIdRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.del_flag</code>. 删除标志
     */
    public final TableField<UcYeepayRequestIdRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "删除标志");

    /**
     * The column <code>xbkj.uc_yeepay_request_id.version</code>.
     */
    public final TableField<UcYeepayRequestIdRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>xbkj.uc_yeepay_request_id</code> table reference
     */
    public UcYeepayRequestId() {
        this(DSL.name("uc_yeepay_request_id"), null);
    }

    /**
     * Create an aliased <code>xbkj.uc_yeepay_request_id</code> table reference
     */
    public UcYeepayRequestId(String alias) {
        this(DSL.name(alias), UC_YEEPAY_REQUEST_ID);
    }

    /**
     * Create an aliased <code>xbkj.uc_yeepay_request_id</code> table reference
     */
    public UcYeepayRequestId(Name alias) {
        this(alias, UC_YEEPAY_REQUEST_ID);
    }

    private UcYeepayRequestId(Name alias, Table<UcYeepayRequestIdRecord> aliased) {
        this(alias, aliased, null);
    }

    private UcYeepayRequestId(Name alias, Table<UcYeepayRequestIdRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Xbkj.XBKJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UC_YEEPAY_REQUEST_ID_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UcYeepayRequestIdRecord> getPrimaryKey() {
        return Keys.KEY_UC_YEEPAY_REQUEST_ID_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UcYeepayRequestIdRecord>> getKeys() {
        return Arrays.<UniqueKey<UcYeepayRequestIdRecord>>asList(Keys.KEY_UC_YEEPAY_REQUEST_ID_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcYeepayRequestId as(String alias) {
        return new UcYeepayRequestId(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcYeepayRequestId as(Name alias) {
        return new UcYeepayRequestId(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UcYeepayRequestId rename(String name) {
        return new UcYeepayRequestId(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UcYeepayRequestId rename(Name name) {
        return new UcYeepayRequestId(name, null);
    }
}
