/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 电商泛金融电商钱包持仓
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdEbusinessPositionFund implements Serializable {

    private static final long serialVersionUID = 470399817;

    private Long       id;
    private Long       accountId;
    private String     code;
    private String     name;
    private String     currency;
    private Long       capital;
    private Long       share;
    private Long       usableShare;
    private String     dividendType;
    private Long       netValue;
    private Date       netValueDate;
    private Long       marketValue;
    private Long       floatingPl;
    private BigDecimal yield;
    private Long       incomeYesterday;
    private Timestamp  createAt;
    private Timestamp  updateAt;
    private Boolean    delFlag;
    private Long       version;

    public FdEbusinessPositionFund() {}

    public FdEbusinessPositionFund(FdEbusinessPositionFund value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.code = value.code;
        this.name = value.name;
        this.currency = value.currency;
        this.capital = value.capital;
        this.share = value.share;
        this.usableShare = value.usableShare;
        this.dividendType = value.dividendType;
        this.netValue = value.netValue;
        this.netValueDate = value.netValueDate;
        this.marketValue = value.marketValue;
        this.floatingPl = value.floatingPl;
        this.yield = value.yield;
        this.incomeYesterday = value.incomeYesterday;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public FdEbusinessPositionFund(
        Long       id,
        Long       accountId,
        String     code,
        String     name,
        String     currency,
        Long       capital,
        Long       share,
        Long       usableShare,
        String     dividendType,
        Long       netValue,
        Date       netValueDate,
        Long       marketValue,
        Long       floatingPl,
        BigDecimal yield,
        Long       incomeYesterday,
        Timestamp  createAt,
        Timestamp  updateAt,
        Boolean    delFlag,
        Long       version
    ) {
        this.id = id;
        this.accountId = accountId;
        this.code = code;
        this.name = name;
        this.currency = currency;
        this.capital = capital;
        this.share = share;
        this.usableShare = usableShare;
        this.dividendType = dividendType;
        this.netValue = netValue;
        this.netValueDate = netValueDate;
        this.marketValue = marketValue;
        this.floatingPl = floatingPl;
        this.yield = yield;
        this.incomeYesterday = incomeYesterday;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Long getCapital() {
        return this.capital;
    }

    public void setCapital(Long capital) {
        this.capital = capital;
    }

    public Long getShare() {
        return this.share;
    }

    public void setShare(Long share) {
        this.share = share;
    }

    public Long getUsableShare() {
        return this.usableShare;
    }

    public void setUsableShare(Long usableShare) {
        this.usableShare = usableShare;
    }

    public String getDividendType() {
        return this.dividendType;
    }

    public void setDividendType(String dividendType) {
        this.dividendType = dividendType;
    }

    public Long getNetValue() {
        return this.netValue;
    }

    public void setNetValue(Long netValue) {
        this.netValue = netValue;
    }

    public Date getNetValueDate() {
        return this.netValueDate;
    }

    public void setNetValueDate(Date netValueDate) {
        this.netValueDate = netValueDate;
    }

    public Long getMarketValue() {
        return this.marketValue;
    }

    public void setMarketValue(Long marketValue) {
        this.marketValue = marketValue;
    }

    public Long getFloatingPl() {
        return this.floatingPl;
    }

    public void setFloatingPl(Long floatingPl) {
        this.floatingPl = floatingPl;
    }

    public BigDecimal getYield() {
        return this.yield;
    }

    public void setYield(BigDecimal yield) {
        this.yield = yield;
    }

    public Long getIncomeYesterday() {
        return this.incomeYesterday;
    }

    public void setIncomeYesterday(Long incomeYesterday) {
        this.incomeYesterday = incomeYesterday;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FdEbusinessPositionFund (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(currency);
        sb.append(", ").append(capital);
        sb.append(", ").append(share);
        sb.append(", ").append(usableShare);
        sb.append(", ").append(dividendType);
        sb.append(", ").append(netValue);
        sb.append(", ").append(netValueDate);
        sb.append(", ").append(marketValue);
        sb.append(", ").append(floatingPl);
        sb.append(", ").append(yield);
        sb.append(", ").append(incomeYesterday);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
