/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 电商信用额度信息(数组),花呗，借呗
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdEbusinessCreditLimit implements Serializable {

    private static final long serialVersionUID = 275789152;

    private Long      id;
    private Long      accountId;
    private String    name;
    private String    admit;
    private String    account;
    private String    creditLimit;
    private String    usableLimit;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean   delFlag;
    private Long      version;

    public FdEbusinessCreditLimit() {}

    public FdEbusinessCreditLimit(FdEbusinessCreditLimit value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.name = value.name;
        this.admit = value.admit;
        this.account = value.account;
        this.creditLimit = value.creditLimit;
        this.usableLimit = value.usableLimit;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public FdEbusinessCreditLimit(
        Long      id,
        Long      accountId,
        String    name,
        String    admit,
        String    account,
        String    creditLimit,
        String    usableLimit,
        Timestamp createAt,
        Timestamp updateAt,
        Boolean   delFlag,
        Long      version
    ) {
        this.id = id;
        this.accountId = accountId;
        this.name = name;
        this.admit = admit;
        this.account = account;
        this.creditLimit = creditLimit;
        this.usableLimit = usableLimit;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAdmit() {
        return this.admit;
    }

    public void setAdmit(String admit) {
        this.admit = admit;
    }

    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getCreditLimit() {
        return this.creditLimit;
    }

    public void setCreditLimit(String creditLimit) {
        this.creditLimit = creditLimit;
    }

    public String getUsableLimit() {
        return this.usableLimit;
    }

    public void setUsableLimit(String usableLimit) {
        this.usableLimit = usableLimit;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FdEbusinessCreditLimit (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(name);
        sb.append(", ").append(admit);
        sb.append(", ").append(account);
        sb.append(", ").append(creditLimit);
        sb.append(", ").append(usableLimit);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
