/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 电商已出账单和未出账单流 信息(数组)(花呗)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdEbusinessBillItems implements Serializable {

    private static final long serialVersionUID = -1319120707;

    private Long      id;
    private Long      accountId;
    private String    billId;
    private String    biztime;
    private String    biztimestr;
    private String    name;
    private String    amount;
    private String    biztype;
    private String    outbizno;
    private String    periodtext;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean   delFlag;
    private Long      version;

    public FdEbusinessBillItems() {}

    public FdEbusinessBillItems(FdEbusinessBillItems value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.billId = value.billId;
        this.biztime = value.biztime;
        this.biztimestr = value.biztimestr;
        this.name = value.name;
        this.amount = value.amount;
        this.biztype = value.biztype;
        this.outbizno = value.outbizno;
        this.periodtext = value.periodtext;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public FdEbusinessBillItems(
        Long      id,
        Long      accountId,
        String    billId,
        String    biztime,
        String    biztimestr,
        String    name,
        String    amount,
        String    biztype,
        String    outbizno,
        String    periodtext,
        Timestamp createAt,
        Timestamp updateAt,
        Boolean   delFlag,
        Long      version
    ) {
        this.id = id;
        this.accountId = accountId;
        this.billId = billId;
        this.biztime = biztime;
        this.biztimestr = biztimestr;
        this.name = name;
        this.amount = amount;
        this.biztype = biztype;
        this.outbizno = outbizno;
        this.periodtext = periodtext;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public String getBillId() {
        return this.billId;
    }

    public void setBillId(String billId) {
        this.billId = billId;
    }

    public String getBiztime() {
        return this.biztime;
    }

    public void setBiztime(String biztime) {
        this.biztime = biztime;
    }

    public String getBiztimestr() {
        return this.biztimestr;
    }

    public void setBiztimestr(String biztimestr) {
        this.biztimestr = biztimestr;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getBiztype() {
        return this.biztype;
    }

    public void setBiztype(String biztype) {
        this.biztype = biztype;
    }

    public String getOutbizno() {
        return this.outbizno;
    }

    public void setOutbizno(String outbizno) {
        this.outbizno = outbizno;
    }

    public String getPeriodtext() {
        return this.periodtext;
    }

    public void setPeriodtext(String periodtext) {
        this.periodtext = periodtext;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FdEbusinessBillItems (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(billId);
        sb.append(", ").append(biztime);
        sb.append(", ").append(biztimestr);
        sb.append(", ").append(name);
        sb.append(", ").append(amount);
        sb.append(", ").append(biztype);
        sb.append(", ").append(outbizno);
        sb.append(", ").append(periodtext);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
