/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 电商未入账单流 信息(数组)(花呗)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdEbusinessUnfinishedBillItems implements Serializable {

    private static final long serialVersionUID = -1125383514;

    private Long      id;
    private Long      accountId;
    private String    billId;
    private String    name;
    private String    alipaytradeno;
    private String    bizdate;
    private String    amount;
    private String    currencycode;
    private String    tradeDescribe;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean   delFlag;
    private Long      version;

    public FdEbusinessUnfinishedBillItems() {}

    public FdEbusinessUnfinishedBillItems(FdEbusinessUnfinishedBillItems value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.billId = value.billId;
        this.name = value.name;
        this.alipaytradeno = value.alipaytradeno;
        this.bizdate = value.bizdate;
        this.amount = value.amount;
        this.currencycode = value.currencycode;
        this.tradeDescribe = value.tradeDescribe;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public FdEbusinessUnfinishedBillItems(
        Long      id,
        Long      accountId,
        String    billId,
        String    name,
        String    alipaytradeno,
        String    bizdate,
        String    amount,
        String    currencycode,
        String    tradeDescribe,
        Timestamp createAt,
        Timestamp updateAt,
        Boolean   delFlag,
        Long      version
    ) {
        this.id = id;
        this.accountId = accountId;
        this.billId = billId;
        this.name = name;
        this.alipaytradeno = alipaytradeno;
        this.bizdate = bizdate;
        this.amount = amount;
        this.currencycode = currencycode;
        this.tradeDescribe = tradeDescribe;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public String getBillId() {
        return this.billId;
    }

    public void setBillId(String billId) {
        this.billId = billId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlipaytradeno() {
        return this.alipaytradeno;
    }

    public void setAlipaytradeno(String alipaytradeno) {
        this.alipaytradeno = alipaytradeno;
    }

    public String getBizdate() {
        return this.bizdate;
    }

    public void setBizdate(String bizdate) {
        this.bizdate = bizdate;
    }

    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getCurrencycode() {
        return this.currencycode;
    }

    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }

    public String getTradeDescribe() {
        return this.tradeDescribe;
    }

    public void setTradeDescribe(String tradeDescribe) {
        this.tradeDescribe = tradeDescribe;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FdEbusinessUnfinishedBillItems (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(billId);
        sb.append(", ").append(name);
        sb.append(", ").append(alipaytradeno);
        sb.append(", ").append(bizdate);
        sb.append(", ").append(amount);
        sb.append(", ").append(currencycode);
        sb.append(", ").append(tradeDescribe);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
