/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 公积金账户信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdFundAccounts implements Serializable {

    private static final long serialVersionUID = -1083079039;

    private Long      id;
    private Long      memberId;
    private String    customer;
    private String    name;
    private String    idcard;
    private String    balance;
    private Timestamp lastRecordDate;
    private String    status;
    private String    company;
    private String    depositAmount;
    private String    depositBase;
    private String    companyRate;
    private String    personRate;
    private String    housingSupplementBase;
    private String    housingSupplementBalance;
    private Timestamp initDate;
    private Long      onceBalance;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean   delFlag;
    private Long      version;

    public FdFundAccounts() {}

    public FdFundAccounts(FdFundAccounts value) {
        this.id = value.id;
        this.memberId = value.memberId;
        this.customer = value.customer;
        this.name = value.name;
        this.idcard = value.idcard;
        this.balance = value.balance;
        this.lastRecordDate = value.lastRecordDate;
        this.status = value.status;
        this.company = value.company;
        this.depositAmount = value.depositAmount;
        this.depositBase = value.depositBase;
        this.companyRate = value.companyRate;
        this.personRate = value.personRate;
        this.housingSupplementBase = value.housingSupplementBase;
        this.housingSupplementBalance = value.housingSupplementBalance;
        this.initDate = value.initDate;
        this.onceBalance = value.onceBalance;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public FdFundAccounts(
        Long      id,
        Long      memberId,
        String    customer,
        String    name,
        String    idcard,
        String    balance,
        Timestamp lastRecordDate,
        String    status,
        String    company,
        String    depositAmount,
        String    depositBase,
        String    companyRate,
        String    personRate,
        String    housingSupplementBase,
        String    housingSupplementBalance,
        Timestamp initDate,
        Long      onceBalance,
        Timestamp createAt,
        Timestamp updateAt,
        Boolean   delFlag,
        Long      version
    ) {
        this.id = id;
        this.memberId = memberId;
        this.customer = customer;
        this.name = name;
        this.idcard = idcard;
        this.balance = balance;
        this.lastRecordDate = lastRecordDate;
        this.status = status;
        this.company = company;
        this.depositAmount = depositAmount;
        this.depositBase = depositBase;
        this.companyRate = companyRate;
        this.personRate = personRate;
        this.housingSupplementBase = housingSupplementBase;
        this.housingSupplementBalance = housingSupplementBalance;
        this.initDate = initDate;
        this.onceBalance = onceBalance;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMemberId() {
        return this.memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public String getCustomer() {
        return this.customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIdcard() {
        return this.idcard;
    }

    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getBalance() {
        return this.balance;
    }

    public void setBalance(String balance) {
        this.balance = balance;
    }

    public Timestamp getLastRecordDate() {
        return this.lastRecordDate;
    }

    public void setLastRecordDate(Timestamp lastRecordDate) {
        this.lastRecordDate = lastRecordDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getDepositAmount() {
        return this.depositAmount;
    }

    public void setDepositAmount(String depositAmount) {
        this.depositAmount = depositAmount;
    }

    public String getDepositBase() {
        return this.depositBase;
    }

    public void setDepositBase(String depositBase) {
        this.depositBase = depositBase;
    }

    public String getCompanyRate() {
        return this.companyRate;
    }

    public void setCompanyRate(String companyRate) {
        this.companyRate = companyRate;
    }

    public String getPersonRate() {
        return this.personRate;
    }

    public void setPersonRate(String personRate) {
        this.personRate = personRate;
    }

    public String getHousingSupplementBase() {
        return this.housingSupplementBase;
    }

    public void setHousingSupplementBase(String housingSupplementBase) {
        this.housingSupplementBase = housingSupplementBase;
    }

    public String getHousingSupplementBalance() {
        return this.housingSupplementBalance;
    }

    public void setHousingSupplementBalance(String housingSupplementBalance) {
        this.housingSupplementBalance = housingSupplementBalance;
    }

    public Timestamp getInitDate() {
        return this.initDate;
    }

    public void setInitDate(Timestamp initDate) {
        this.initDate = initDate;
    }

    public Long getOnceBalance() {
        return this.onceBalance;
    }

    public void setOnceBalance(Long onceBalance) {
        this.onceBalance = onceBalance;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FdFundAccounts (");

        sb.append(id);
        sb.append(", ").append(memberId);
        sb.append(", ").append(customer);
        sb.append(", ").append(name);
        sb.append(", ").append(idcard);
        sb.append(", ").append(balance);
        sb.append(", ").append(lastRecordDate);
        sb.append(", ").append(status);
        sb.append(", ").append(company);
        sb.append(", ").append(depositAmount);
        sb.append(", ").append(depositBase);
        sb.append(", ").append(companyRate);
        sb.append(", ").append(personRate);
        sb.append(", ").append(housingSupplementBase);
        sb.append(", ").append(housingSupplementBalance);
        sb.append(", ").append(initDate);
        sb.append(", ").append(onceBalance);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
