/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 静默信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdProviderSilentInfos implements Serializable {

    private static final long serialVersionUID = 2036273114;

    private Long      id;
    private Long      accountId;
    private String    period;
    private String    count;
    private String    days;
    private String    maxContinuousCount;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean   delFlag;
    private Long      version;

    public FdProviderSilentInfos() {}

    public FdProviderSilentInfos(FdProviderSilentInfos value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.period = value.period;
        this.count = value.count;
        this.days = value.days;
        this.maxContinuousCount = value.maxContinuousCount;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public FdProviderSilentInfos(
        Long      id,
        Long      accountId,
        String    period,
        String    count,
        String    days,
        String    maxContinuousCount,
        Timestamp createAt,
        Timestamp updateAt,
        Boolean   delFlag,
        Long      version
    ) {
        this.id = id;
        this.accountId = accountId;
        this.period = period;
        this.count = count;
        this.days = days;
        this.maxContinuousCount = maxContinuousCount;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public String getPeriod() {
        return this.period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public String getCount() {
        return this.count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getDays() {
        return this.days;
    }

    public void setDays(String days) {
        this.days = days;
    }

    public String getMaxContinuousCount() {
        return this.maxContinuousCount;
    }

    public void setMaxContinuousCount(String maxContinuousCount) {
        this.maxContinuousCount = maxContinuousCount;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FdProviderSilentInfos (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(period);
        sb.append(", ").append(count);
        sb.append(", ").append(days);
        sb.append(", ").append(maxContinuousCount);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
