/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 公积金数据报告基本信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdReportFundInfo implements Serializable {

    private static final long serialVersionUID = -414627636;

    private Long       id;
    private Long       organizationId;
    private String     customerId;
    private String     organizationType;
    private String     name;
    private String     idcard;
    private String     status;
    private String     company;
    private BigDecimal depositRate;
    private BigDecimal depositAmount;
    private BigDecimal balance;
    private String     lastRecordDate;
    private String     continuousDepositMonth;
    private String     lastDepositMonth;
    private Long       loanCount;
    private BigDecimal loanRepayAmount;
    private BigDecimal monthlyIncome;
    private String     currentCorpContinuousDepositMonth;
    private String     corpType;
    private String     corpScale;
    private String     userName;
    private String     userIdcard;
    private String     userPhone;
    private String     nameMatch;
    private String     idcardMatch;
    private Timestamp  createAt;
    private Timestamp  updateAt;
    private Boolean    delFlag;
    private Long       version;

    public FdReportFundInfo() {}

    public FdReportFundInfo(FdReportFundInfo value) {
        this.id = value.id;
        this.organizationId = value.organizationId;
        this.customerId = value.customerId;
        this.organizationType = value.organizationType;
        this.name = value.name;
        this.idcard = value.idcard;
        this.status = value.status;
        this.company = value.company;
        this.depositRate = value.depositRate;
        this.depositAmount = value.depositAmount;
        this.balance = value.balance;
        this.lastRecordDate = value.lastRecordDate;
        this.continuousDepositMonth = value.continuousDepositMonth;
        this.lastDepositMonth = value.lastDepositMonth;
        this.loanCount = value.loanCount;
        this.loanRepayAmount = value.loanRepayAmount;
        this.monthlyIncome = value.monthlyIncome;
        this.currentCorpContinuousDepositMonth = value.currentCorpContinuousDepositMonth;
        this.corpType = value.corpType;
        this.corpScale = value.corpScale;
        this.userName = value.userName;
        this.userIdcard = value.userIdcard;
        this.userPhone = value.userPhone;
        this.nameMatch = value.nameMatch;
        this.idcardMatch = value.idcardMatch;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public FdReportFundInfo(
        Long       id,
        Long       organizationId,
        String     customerId,
        String     organizationType,
        String     name,
        String     idcard,
        String     status,
        String     company,
        BigDecimal depositRate,
        BigDecimal depositAmount,
        BigDecimal balance,
        String     lastRecordDate,
        String     continuousDepositMonth,
        String     lastDepositMonth,
        Long       loanCount,
        BigDecimal loanRepayAmount,
        BigDecimal monthlyIncome,
        String     currentCorpContinuousDepositMonth,
        String     corpType,
        String     corpScale,
        String     userName,
        String     userIdcard,
        String     userPhone,
        String     nameMatch,
        String     idcardMatch,
        Timestamp  createAt,
        Timestamp  updateAt,
        Boolean    delFlag,
        Long       version
    ) {
        this.id = id;
        this.organizationId = organizationId;
        this.customerId = customerId;
        this.organizationType = organizationType;
        this.name = name;
        this.idcard = idcard;
        this.status = status;
        this.company = company;
        this.depositRate = depositRate;
        this.depositAmount = depositAmount;
        this.balance = balance;
        this.lastRecordDate = lastRecordDate;
        this.continuousDepositMonth = continuousDepositMonth;
        this.lastDepositMonth = lastDepositMonth;
        this.loanCount = loanCount;
        this.loanRepayAmount = loanRepayAmount;
        this.monthlyIncome = monthlyIncome;
        this.currentCorpContinuousDepositMonth = currentCorpContinuousDepositMonth;
        this.corpType = corpType;
        this.corpScale = corpScale;
        this.userName = userName;
        this.userIdcard = userIdcard;
        this.userPhone = userPhone;
        this.nameMatch = nameMatch;
        this.idcardMatch = idcardMatch;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrganizationId() {
        return this.organizationId;
    }

    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    public String getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getOrganizationType() {
        return this.organizationType;
    }

    public void setOrganizationType(String organizationType) {
        this.organizationType = organizationType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIdcard() {
        return this.idcard;
    }

    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public BigDecimal getDepositRate() {
        return this.depositRate;
    }

    public void setDepositRate(BigDecimal depositRate) {
        this.depositRate = depositRate;
    }

    public BigDecimal getDepositAmount() {
        return this.depositAmount;
    }

    public void setDepositAmount(BigDecimal depositAmount) {
        this.depositAmount = depositAmount;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public String getLastRecordDate() {
        return this.lastRecordDate;
    }

    public void setLastRecordDate(String lastRecordDate) {
        this.lastRecordDate = lastRecordDate;
    }

    public String getContinuousDepositMonth() {
        return this.continuousDepositMonth;
    }

    public void setContinuousDepositMonth(String continuousDepositMonth) {
        this.continuousDepositMonth = continuousDepositMonth;
    }

    public String getLastDepositMonth() {
        return this.lastDepositMonth;
    }

    public void setLastDepositMonth(String lastDepositMonth) {
        this.lastDepositMonth = lastDepositMonth;
    }

    public Long getLoanCount() {
        return this.loanCount;
    }

    public void setLoanCount(Long loanCount) {
        this.loanCount = loanCount;
    }

    public BigDecimal getLoanRepayAmount() {
        return this.loanRepayAmount;
    }

    public void setLoanRepayAmount(BigDecimal loanRepayAmount) {
        this.loanRepayAmount = loanRepayAmount;
    }

    public BigDecimal getMonthlyIncome() {
        return this.monthlyIncome;
    }

    public void setMonthlyIncome(BigDecimal monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }

    public String getCurrentCorpContinuousDepositMonth() {
        return this.currentCorpContinuousDepositMonth;
    }

    public void setCurrentCorpContinuousDepositMonth(String currentCorpContinuousDepositMonth) {
        this.currentCorpContinuousDepositMonth = currentCorpContinuousDepositMonth;
    }

    public String getCorpType() {
        return this.corpType;
    }

    public void setCorpType(String corpType) {
        this.corpType = corpType;
    }

    public String getCorpScale() {
        return this.corpScale;
    }

    public void setCorpScale(String corpScale) {
        this.corpScale = corpScale;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserIdcard() {
        return this.userIdcard;
    }

    public void setUserIdcard(String userIdcard) {
        this.userIdcard = userIdcard;
    }

    public String getUserPhone() {
        return this.userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getNameMatch() {
        return this.nameMatch;
    }

    public void setNameMatch(String nameMatch) {
        this.nameMatch = nameMatch;
    }

    public String getIdcardMatch() {
        return this.idcardMatch;
    }

    public void setIdcardMatch(String idcardMatch) {
        this.idcardMatch = idcardMatch;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FdReportFundInfo (");

        sb.append(id);
        sb.append(", ").append(organizationId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(organizationType);
        sb.append(", ").append(name);
        sb.append(", ").append(idcard);
        sb.append(", ").append(status);
        sb.append(", ").append(company);
        sb.append(", ").append(depositRate);
        sb.append(", ").append(depositAmount);
        sb.append(", ").append(balance);
        sb.append(", ").append(lastRecordDate);
        sb.append(", ").append(continuousDepositMonth);
        sb.append(", ").append(lastDepositMonth);
        sb.append(", ").append(loanCount);
        sb.append(", ").append(loanRepayAmount);
        sb.append(", ").append(monthlyIncome);
        sb.append(", ").append(currentCorpContinuousDepositMonth);
        sb.append(", ").append(corpType);
        sb.append(", ").append(corpScale);
        sb.append(", ").append(userName);
        sb.append(", ").append(userIdcard);
        sb.append(", ").append(userPhone);
        sb.append(", ").append(nameMatch);
        sb.append(", ").append(idcardMatch);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
