/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 缴存流水表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdSocialsecurityFlows implements Serializable {

    private static final long serialVersionUID = 1230732410;

    private Long      id;
    private Long      accountId;
    private String    standardName;
    private String    originName;
    private String    startPaymentMonth;
    private String    endPaymentMonth;
    private String    paymentType;
    private String    paymentBase;
    private String    personAmount;
    private String    companyAmount;
    private String    company;
    private String    accountFlag;
    private String    accountMonth;
    private String    period;
    private String    amonut;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean   delFlag;
    private Long      version;
    private String    operateMoth;

    public FdSocialsecurityFlows() {}

    public FdSocialsecurityFlows(FdSocialsecurityFlows value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.standardName = value.standardName;
        this.originName = value.originName;
        this.startPaymentMonth = value.startPaymentMonth;
        this.endPaymentMonth = value.endPaymentMonth;
        this.paymentType = value.paymentType;
        this.paymentBase = value.paymentBase;
        this.personAmount = value.personAmount;
        this.companyAmount = value.companyAmount;
        this.company = value.company;
        this.accountFlag = value.accountFlag;
        this.accountMonth = value.accountMonth;
        this.period = value.period;
        this.amonut = value.amonut;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
        this.operateMoth = value.operateMoth;
    }

    public FdSocialsecurityFlows(
        Long      id,
        Long      accountId,
        String    standardName,
        String    originName,
        String    startPaymentMonth,
        String    endPaymentMonth,
        String    paymentType,
        String    paymentBase,
        String    personAmount,
        String    companyAmount,
        String    company,
        String    accountFlag,
        String    accountMonth,
        String    period,
        String    amonut,
        Timestamp createAt,
        Timestamp updateAt,
        Boolean   delFlag,
        Long      version,
        String    operateMoth
    ) {
        this.id = id;
        this.accountId = accountId;
        this.standardName = standardName;
        this.originName = originName;
        this.startPaymentMonth = startPaymentMonth;
        this.endPaymentMonth = endPaymentMonth;
        this.paymentType = paymentType;
        this.paymentBase = paymentBase;
        this.personAmount = personAmount;
        this.companyAmount = companyAmount;
        this.company = company;
        this.accountFlag = accountFlag;
        this.accountMonth = accountMonth;
        this.period = period;
        this.amonut = amonut;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
        this.operateMoth = operateMoth;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public String getStandardName() {
        return this.standardName;
    }

    public void setStandardName(String standardName) {
        this.standardName = standardName;
    }

    public String getOriginName() {
        return this.originName;
    }

    public void setOriginName(String originName) {
        this.originName = originName;
    }

    public String getStartPaymentMonth() {
        return this.startPaymentMonth;
    }

    public void setStartPaymentMonth(String startPaymentMonth) {
        this.startPaymentMonth = startPaymentMonth;
    }

    public String getEndPaymentMonth() {
        return this.endPaymentMonth;
    }

    public void setEndPaymentMonth(String endPaymentMonth) {
        this.endPaymentMonth = endPaymentMonth;
    }

    public String getPaymentType() {
        return this.paymentType;
    }

    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    public String getPaymentBase() {
        return this.paymentBase;
    }

    public void setPaymentBase(String paymentBase) {
        this.paymentBase = paymentBase;
    }

    public String getPersonAmount() {
        return this.personAmount;
    }

    public void setPersonAmount(String personAmount) {
        this.personAmount = personAmount;
    }

    public String getCompanyAmount() {
        return this.companyAmount;
    }

    public void setCompanyAmount(String companyAmount) {
        this.companyAmount = companyAmount;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getAccountFlag() {
        return this.accountFlag;
    }

    public void setAccountFlag(String accountFlag) {
        this.accountFlag = accountFlag;
    }

    public String getAccountMonth() {
        return this.accountMonth;
    }

    public void setAccountMonth(String accountMonth) {
        this.accountMonth = accountMonth;
    }

    public String getPeriod() {
        return this.period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public String getAmonut() {
        return this.amonut;
    }

    public void setAmonut(String amonut) {
        this.amonut = amonut;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getOperateMoth() {
        return this.operateMoth;
    }

    public void setOperateMoth(String operateMoth) {
        this.operateMoth = operateMoth;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FdSocialsecurityFlows (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(standardName);
        sb.append(", ").append(originName);
        sb.append(", ").append(startPaymentMonth);
        sb.append(", ").append(endPaymentMonth);
        sb.append(", ").append(paymentType);
        sb.append(", ").append(paymentBase);
        sb.append(", ").append(personAmount);
        sb.append(", ").append(companyAmount);
        sb.append(", ").append(company);
        sb.append(", ").append(accountFlag);
        sb.append(", ").append(accountMonth);
        sb.append(", ").append(period);
        sb.append(", ").append(amonut);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);
        sb.append(", ").append(operateMoth);

        sb.append(")");
        return sb.toString();
    }
}
