/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 用户-角色
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRole implements Serializable {

    private static final long serialVersionUID = -183339949;

    private Long id;
    private Long sysUserId;
    private Long sysRoleId;

    public SysUserRole() {}

    public SysUserRole(SysUserRole value) {
        this.id = value.id;
        this.sysUserId = value.sysUserId;
        this.sysRoleId = value.sysRoleId;
    }

    public SysUserRole(
        Long id,
        Long sysUserId,
        Long sysRoleId
    ) {
        this.id = id;
        this.sysUserId = sysUserId;
        this.sysRoleId = sysRoleId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSysUserId() {
        return this.sysUserId;
    }

    public void setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
    }

    public Long getSysRoleId() {
        return this.sysRoleId;
    }

    public void setSysRoleId(Long sysRoleId) {
        this.sysRoleId = sysRoleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserRole (");

        sb.append(id);
        sb.append(", ").append(sysUserId);
        sb.append(", ").append(sysRoleId);

        sb.append(")");
        return sb.toString();
    }
}
