/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 学历表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcMemberDegree implements Serializable {

    private static final long serialVersionUID = -388064983;

    private Long      id;
    private Long      memberId;
    private String    degree;
    private String    startTime;
    private String    graduateTime;
    private String    iskeySubject;
    private String    levelNo;
    private String    studyResult;
    private String    studyStyle;
    private String    studyType;
    private String    specialty;
    private String    photo;
    private String    photoStyle;
    private String    college;
    private Timestamp createAt;
    private Timestamp updateAt;
    private Boolean   delFlag;
    private Long      version;

    public UcMemberDegree() {}

    public UcMemberDegree(UcMemberDegree value) {
        this.id = value.id;
        this.memberId = value.memberId;
        this.degree = value.degree;
        this.startTime = value.startTime;
        this.graduateTime = value.graduateTime;
        this.iskeySubject = value.iskeySubject;
        this.levelNo = value.levelNo;
        this.studyResult = value.studyResult;
        this.studyStyle = value.studyStyle;
        this.studyType = value.studyType;
        this.specialty = value.specialty;
        this.photo = value.photo;
        this.photoStyle = value.photoStyle;
        this.college = value.college;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public UcMemberDegree(
        Long      id,
        Long      memberId,
        String    degree,
        String    startTime,
        String    graduateTime,
        String    iskeySubject,
        String    levelNo,
        String    studyResult,
        String    studyStyle,
        String    studyType,
        String    specialty,
        String    photo,
        String    photoStyle,
        String    college,
        Timestamp createAt,
        Timestamp updateAt,
        Boolean   delFlag,
        Long      version
    ) {
        this.id = id;
        this.memberId = memberId;
        this.degree = degree;
        this.startTime = startTime;
        this.graduateTime = graduateTime;
        this.iskeySubject = iskeySubject;
        this.levelNo = levelNo;
        this.studyResult = studyResult;
        this.studyStyle = studyStyle;
        this.studyType = studyType;
        this.specialty = specialty;
        this.photo = photo;
        this.photoStyle = photoStyle;
        this.college = college;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMemberId() {
        return this.memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    public String getDegree() {
        return this.degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getStartTime() {
        return this.startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getGraduateTime() {
        return this.graduateTime;
    }

    public void setGraduateTime(String graduateTime) {
        this.graduateTime = graduateTime;
    }

    public String getIskeySubject() {
        return this.iskeySubject;
    }

    public void setIskeySubject(String iskeySubject) {
        this.iskeySubject = iskeySubject;
    }

    public String getLevelNo() {
        return this.levelNo;
    }

    public void setLevelNo(String levelNo) {
        this.levelNo = levelNo;
    }

    public String getStudyResult() {
        return this.studyResult;
    }

    public void setStudyResult(String studyResult) {
        this.studyResult = studyResult;
    }

    public String getStudyStyle() {
        return this.studyStyle;
    }

    public void setStudyStyle(String studyStyle) {
        this.studyStyle = studyStyle;
    }

    public String getStudyType() {
        return this.studyType;
    }

    public void setStudyType(String studyType) {
        this.studyType = studyType;
    }

    public String getSpecialty() {
        return this.specialty;
    }

    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getPhotoStyle() {
        return this.photoStyle;
    }

    public void setPhotoStyle(String photoStyle) {
        this.photoStyle = photoStyle;
    }

    public String getCollege() {
        return this.college;
    }

    public void setCollege(String college) {
        this.college = college;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UcMemberDegree (");

        sb.append(id);
        sb.append(", ").append(memberId);
        sb.append(", ").append(degree);
        sb.append(", ").append(startTime);
        sb.append(", ").append(graduateTime);
        sb.append(", ").append(iskeySubject);
        sb.append(", ").append(levelNo);
        sb.append(", ").append(studyResult);
        sb.append(", ").append(studyStyle);
        sb.append(", ").append(studyType);
        sb.append(", ").append(specialty);
        sb.append(", ").append(photo);
        sb.append(", ").append(photoStyle);
        sb.append(", ").append(college);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
