/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import com.jooq.domain.enums.UcShopTeacherStatus;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 教师列表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcShopTeacher implements Serializable {

    private static final long serialVersionUID = -1221520879;

    private Long                id;
    private Long                shopId;
    private String              name;
    private String              headUrl;
    private String              professionalTitle;
    private UcShopTeacherStatus status;
    private String              infro;
    private String              detailIntro;
    private Timestamp           createAt;
    private Timestamp           updateAt;
    private Boolean             delFlag;
    private Long                version;

    public UcShopTeacher() {}

    public UcShopTeacher(UcShopTeacher value) {
        this.id = value.id;
        this.shopId = value.shopId;
        this.name = value.name;
        this.headUrl = value.headUrl;
        this.professionalTitle = value.professionalTitle;
        this.status = value.status;
        this.infro = value.infro;
        this.detailIntro = value.detailIntro;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public UcShopTeacher(
        Long                id,
        Long                shopId,
        String              name,
        String              headUrl,
        String              professionalTitle,
        UcShopTeacherStatus status,
        String              infro,
        String              detailIntro,
        Timestamp           createAt,
        Timestamp           updateAt,
        Boolean             delFlag,
        Long                version
    ) {
        this.id = id;
        this.shopId = shopId;
        this.name = name;
        this.headUrl = headUrl;
        this.professionalTitle = professionalTitle;
        this.status = status;
        this.infro = infro;
        this.detailIntro = detailIntro;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getShopId() {
        return this.shopId;
    }

    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getHeadUrl() {
        return this.headUrl;
    }

    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl;
    }

    public String getProfessionalTitle() {
        return this.professionalTitle;
    }

    public void setProfessionalTitle(String professionalTitle) {
        this.professionalTitle = professionalTitle;
    }

    public UcShopTeacherStatus getStatus() {
        return this.status;
    }

    public void setStatus(UcShopTeacherStatus status) {
        this.status = status;
    }

    public String getInfro() {
        return this.infro;
    }

    public void setInfro(String infro) {
        this.infro = infro;
    }

    public String getDetailIntro() {
        return this.detailIntro;
    }

    public void setDetailIntro(String detailIntro) {
        this.detailIntro = detailIntro;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UcShopTeacher (");

        sb.append(id);
        sb.append(", ").append(shopId);
        sb.append(", ").append(name);
        sb.append(", ").append(headUrl);
        sb.append(", ").append(professionalTitle);
        sb.append(", ").append(status);
        sb.append(", ").append(infro);
        sb.append(", ").append(detailIntro);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
