/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.pojos;


import com.jooq.domain.enums.YeepayPayOrderPayStatus;
import com.jooq.domain.enums.YeepayPayOrderPayType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 易宝支付表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YeepayPayOrder implements Serializable {

    private static final long serialVersionUID = 1380531673;

    private Long                    id;
    private String                  identityid;
    private Long                    ucMemberId;
    private String                  requestno;
    private String                  h5directpaytype;
    private Long                    ucBankId;
    private String                  productname;
    private String                  amount;
    private String                  dividejstr;
    private YeepayPayOrderPayType   payType;
    private YeepayPayOrderPayStatus payStatus;
    private String                  sourceids;
    private String                  extinfos;
    private String                  remark;
    private Timestamp               createAt;
    private Timestamp               updateAt;
    private Boolean                 delFlag;
    private Long                    version;

    public YeepayPayOrder() {}

    public YeepayPayOrder(YeepayPayOrder value) {
        this.id = value.id;
        this.identityid = value.identityid;
        this.ucMemberId = value.ucMemberId;
        this.requestno = value.requestno;
        this.h5directpaytype = value.h5directpaytype;
        this.ucBankId = value.ucBankId;
        this.productname = value.productname;
        this.amount = value.amount;
        this.dividejstr = value.dividejstr;
        this.payType = value.payType;
        this.payStatus = value.payStatus;
        this.sourceids = value.sourceids;
        this.extinfos = value.extinfos;
        this.remark = value.remark;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
        this.delFlag = value.delFlag;
        this.version = value.version;
    }

    public YeepayPayOrder(
        Long                    id,
        String                  identityid,
        Long                    ucMemberId,
        String                  requestno,
        String                  h5directpaytype,
        Long                    ucBankId,
        String                  productname,
        String                  amount,
        String                  dividejstr,
        YeepayPayOrderPayType   payType,
        YeepayPayOrderPayStatus payStatus,
        String                  sourceids,
        String                  extinfos,
        String                  remark,
        Timestamp               createAt,
        Timestamp               updateAt,
        Boolean                 delFlag,
        Long                    version
    ) {
        this.id = id;
        this.identityid = identityid;
        this.ucMemberId = ucMemberId;
        this.requestno = requestno;
        this.h5directpaytype = h5directpaytype;
        this.ucBankId = ucBankId;
        this.productname = productname;
        this.amount = amount;
        this.dividejstr = dividejstr;
        this.payType = payType;
        this.payStatus = payStatus;
        this.sourceids = sourceids;
        this.extinfos = extinfos;
        this.remark = remark;
        this.createAt = createAt;
        this.updateAt = updateAt;
        this.delFlag = delFlag;
        this.version = version;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentityid() {
        return this.identityid;
    }

    public void setIdentityid(String identityid) {
        this.identityid = identityid;
    }

    public Long getUcMemberId() {
        return this.ucMemberId;
    }

    public void setUcMemberId(Long ucMemberId) {
        this.ucMemberId = ucMemberId;
    }

    public String getRequestno() {
        return this.requestno;
    }

    public void setRequestno(String requestno) {
        this.requestno = requestno;
    }

    public String getH5directpaytype() {
        return this.h5directpaytype;
    }

    public void setH5directpaytype(String h5directpaytype) {
        this.h5directpaytype = h5directpaytype;
    }

    public Long getUcBankId() {
        return this.ucBankId;
    }

    public void setUcBankId(Long ucBankId) {
        this.ucBankId = ucBankId;
    }

    public String getProductname() {
        return this.productname;
    }

    public void setProductname(String productname) {
        this.productname = productname;
    }

    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getDividejstr() {
        return this.dividejstr;
    }

    public void setDividejstr(String dividejstr) {
        this.dividejstr = dividejstr;
    }

    public YeepayPayOrderPayType getPayType() {
        return this.payType;
    }

    public void setPayType(YeepayPayOrderPayType payType) {
        this.payType = payType;
    }

    public YeepayPayOrderPayStatus getPayStatus() {
        return this.payStatus;
    }

    public void setPayStatus(YeepayPayOrderPayStatus payStatus) {
        this.payStatus = payStatus;
    }

    public String getSourceids() {
        return this.sourceids;
    }

    public void setSourceids(String sourceids) {
        this.sourceids = sourceids;
    }

    public String getExtinfos() {
        return this.extinfos;
    }

    public void setExtinfos(String extinfos) {
        this.extinfos = extinfos;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public void setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
    }

    public Boolean getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("YeepayPayOrder (");

        sb.append(id);
        sb.append(", ").append(identityid);
        sb.append(", ").append(ucMemberId);
        sb.append(", ").append(requestno);
        sb.append(", ").append(h5directpaytype);
        sb.append(", ").append(ucBankId);
        sb.append(", ").append(productname);
        sb.append(", ").append(amount);
        sb.append(", ").append(dividejstr);
        sb.append(", ").append(payType);
        sb.append(", ").append(payStatus);
        sb.append(", ").append(sourceids);
        sb.append(", ").append(extinfos);
        sb.append(", ").append(remark);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
