/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.enums.CmsBannerLocation;
import com.jooq.domain.enums.CmsBannerStatus;
import com.jooq.domain.tables.CmsBanner;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * banner管理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsBannerRecord extends UpdatableRecordImpl<CmsBannerRecord> {

    private static final long serialVersionUID = -204368363;

    /**
     * Setter for <code>xbkj.cms_banner.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.cms_banner.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xbkj.cms_banner.location</code>. 启动/闪屏页(APP);首页活动;弹出框活动；首页(APP/PC);
     */
    public void setLocation(CmsBannerLocation value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.location</code>. 启动/闪屏页(APP);首页活动;弹出框活动；首页(APP/PC);
     */
    public CmsBannerLocation getLocation() {
        return (CmsBannerLocation) get(2);
    }

    /**
     * Setter for <code>xbkj.cms_banner.image</code>. banner图片(jpg、png)
     */
    public void setImage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.image</code>. banner图片(jpg、png)
     */
    public String getImage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xbkj.cms_banner.image_bg</code>. 动态banner的底图
     */
    public void setImageBg(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.image_bg</code>. 动态banner的底图
     */
    public String getImageBg() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xbkj.cms_banner.href</code>. 链接
     */
    public void setHref(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.href</code>. 链接
     */
    public String getHref() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xbkj.cms_banner.status</code>. online表示上线,saved表示保存, offline表示下线
     */
    public void setStatus(CmsBannerStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.status</code>. online表示上线,saved表示保存, offline表示下线
     */
    public CmsBannerStatus getStatus() {
        return (CmsBannerStatus) get(6);
    }

    /**
     * Setter for <code>xbkj.cms_banner.priority</code>. 展示优先级
     */
    public void setPriority(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.priority</code>. 展示优先级
     */
    public Integer getPriority() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>xbkj.cms_banner.jump_type</code>. 跳转类型
     */
    public void setJumpType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.jump_type</code>. 跳转类型
     */
    public String getJumpType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>xbkj.cms_banner.start_time</code>. 开始时间
     */
    public void setStartTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.start_time</code>. 开始时间
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>xbkj.cms_banner.end_time</code>. 结束时间
     */
    public void setEndTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.end_time</code>. 结束时间
     */
    public Timestamp getEndTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>xbkj.cms_banner.target_blank</code>. 新窗口打开（0:否 1:是），默认否
     */
    public void setTargetBlank(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.target_blank</code>. 新窗口打开（0:否 1:是），默认否
     */
    public Boolean getTargetBlank() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>xbkj.cms_banner.share_flag</code>. 是否分享标记
     */
    public void setShareFlag(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.share_flag</code>. 是否分享标记
     */
    public Boolean getShareFlag() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>xbkj.cms_banner.share_title</code>. 分享标题
     */
    public void setShareTitle(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.share_title</code>. 分享标题
     */
    public String getShareTitle() {
        return (String) get(13);
    }

    /**
     * Setter for <code>xbkj.cms_banner.share_word</code>. 分享文案
     */
    public void setShareWord(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.share_word</code>. 分享文案
     */
    public String getShareWord() {
        return (String) get(14);
    }

    /**
     * Setter for <code>xbkj.cms_banner.pc_view</code>. pc端显示（0-不显示 1-显示）
     */
    public void setPcView(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.pc_view</code>. pc端显示（0-不显示 1-显示）
     */
    public Boolean getPcView() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>xbkj.cms_banner.app_view</code>. app端显示（0-不显示 1-显示）
     */
    public void setAppView(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.app_view</code>. app端显示（0-不显示 1-显示）
     */
    public Boolean getAppView() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>xbkj.cms_banner.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>xbkj.cms_banner.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>xbkj.cms_banner.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>xbkj.cms_banner.version</code>.
     */
    public void setVersion(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.version</code>.
     */
    public Long getVersion() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>xbkj.cms_banner.banner_type</code>. 是否金融类的活动，默认非金融类
     */
    public void setBannerType(Boolean value) {
        set(21, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.banner_type</code>. 是否金融类的活动，默认非金融类
     */
    public Boolean getBannerType() {
        return (Boolean) get(21);
    }

    /**
     * Setter for <code>xbkj.cms_banner.extend_field</code>. 扩展字段
     */
    public void setExtendField(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.extend_field</code>. 扩展字段
     */
    public String getExtendField() {
        return (String) get(22);
    }

    /**
     * Setter for <code>xbkj.cms_banner.special</code>. 是否专题的活动，默认非专题
     */
    public void setSpecial(Boolean value) {
        set(23, value);
    }

    /**
     * Getter for <code>xbkj.cms_banner.special</code>. 是否专题的活动，默认非专题
     */
    public Boolean getSpecial() {
        return (Boolean) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmsBannerRecord
     */
    public CmsBannerRecord() {
        super(CmsBanner.CMS_BANNER);
    }

    /**
     * Create a detached, initialised CmsBannerRecord
     */
    public CmsBannerRecord(Long id, String name, CmsBannerLocation location, String image, String imageBg, String href, CmsBannerStatus status, Integer priority, String jumpType, Timestamp startTime, Timestamp endTime, Boolean targetBlank, Boolean shareFlag, String shareTitle, String shareWord, Boolean pcView, Boolean appView, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version, Boolean bannerType, String extendField, Boolean special) {
        super(CmsBanner.CMS_BANNER);

        set(0, id);
        set(1, name);
        set(2, location);
        set(3, image);
        set(4, imageBg);
        set(5, href);
        set(6, status);
        set(7, priority);
        set(8, jumpType);
        set(9, startTime);
        set(10, endTime);
        set(11, targetBlank);
        set(12, shareFlag);
        set(13, shareTitle);
        set(14, shareWord);
        set(15, pcView);
        set(16, appView);
        set(17, createAt);
        set(18, updateAt);
        set(19, delFlag);
        set(20, version);
        set(21, bannerType);
        set(22, extendField);
        set(23, special);
    }
}
