/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.tables.FdProviderPhonalyzr;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通话分析表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdProviderPhonalyzrRecord extends UpdatableRecordImpl<FdProviderPhonalyzrRecord> implements Record17<Long, Long, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = -1315761204;

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.account_id</code>. 账户id
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.account_id</code>. 账户id
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.period</code>. 时间范围（1个月/3个月/6个月）
     */
    public void setPeriod(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.period</code>. 时间范围（1个月/3个月/6个月）
     */
    public String getPeriod() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.call_number</code>. 对方号码数
     */
    public void setCallNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.call_number</code>. 对方号码数
     */
    public String getCallNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.interphone_count</code>. 互通电话号码数
     */
    public void setInterphoneCount(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.interphone_count</code>. 互通电话号码数
     */
    public String getInterphoneCount() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.interphone_rate</code>. 互通电话号码占比
     */
    public void setInterphoneRate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.interphone_rate</code>. 互通电话号码占比
     */
    public String getInterphoneRate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.calling_count</code>. 主叫对方号码数
     */
    public void setCallingCount(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.calling_count</code>. 主叫对方号码数
     */
    public String getCallingCount() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.calling_rate</code>. 主叫对方号码占比
     */
    public void setCallingRate(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.calling_rate</code>. 主叫对方号码占比
     */
    public String getCallingRate() {
        return (String) get(7);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.called_count</code>. 被叫对方号码数
     */
    public void setCalledCount(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.called_count</code>. 被叫对方号码数
     */
    public String getCalledCount() {
        return (String) get(8);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.called_rate</code>. 被叫对方号码占比
     */
    public void setCalledRate(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.called_rate</code>. 被叫对方号码占比
     */
    public String getCalledRate() {
        return (String) get(9);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.count</code>. 通话总次数
     */
    public void setCount(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.count</code>. 通话总次数
     */
    public String getCount() {
        return (String) get(10);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.morning_count</code>. 凌晨通话次数(00-06)
     */
    public void setMorningCount(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.morning_count</code>. 凌晨通话次数(00-06)
     */
    public String getMorningCount() {
        return (String) get(11);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.morning_call_rate</code>. 凌晨通话次数占比
     */
    public void setMorningCallRate(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.morning_call_rate</code>. 凌晨通话次数占比
     */
    public String getMorningCallRate() {
        return (String) get(12);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>xbkj.fd_provider_phonalyzr.version</code>.
     */
    public void setVersion(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_phonalyzr.version</code>.
     */
    public Long getVersion() {
        return (Long) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, Long, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, Long, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.PERIOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.CALL_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.INTERPHONE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.INTERPHONE_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.CALLING_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.CALLING_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.CALLED_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.CALLED_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.MORNING_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.MORNING_CALL_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field16() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCallNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getInterphoneCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getInterphoneRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCallingCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCallingRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCalledCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCalledRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getMorningCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getMorningCallRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component16() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component17() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCallNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInterphoneCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getInterphoneRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCallingCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCallingRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCalledCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCalledRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getMorningCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getMorningCallRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value16() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value2(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value3(String value) {
        setPeriod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value4(String value) {
        setCallNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value5(String value) {
        setInterphoneCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value6(String value) {
        setInterphoneRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value7(String value) {
        setCallingCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value8(String value) {
        setCallingRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value9(String value) {
        setCalledCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value10(String value) {
        setCalledRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value11(String value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value12(String value) {
        setMorningCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value13(String value) {
        setMorningCallRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value14(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value15(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value16(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord value17(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderPhonalyzrRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, Timestamp value14, Timestamp value15, Boolean value16, Long value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FdProviderPhonalyzrRecord
     */
    public FdProviderPhonalyzrRecord() {
        super(FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR);
    }

    /**
     * Create a detached, initialised FdProviderPhonalyzrRecord
     */
    public FdProviderPhonalyzrRecord(Long id, Long accountId, String period, String callNumber, String interphoneCount, String interphoneRate, String callingCount, String callingRate, String calledCount, String calledRate, String count, String morningCount, String morningCallRate, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(FdProviderPhonalyzr.FD_PROVIDER_PHONALYZR);

        set(0, id);
        set(1, accountId);
        set(2, period);
        set(3, callNumber);
        set(4, interphoneCount);
        set(5, interphoneRate);
        set(6, callingCount);
        set(7, callingRate);
        set(8, calledCount);
        set(9, calledRate);
        set(10, count);
        set(11, morningCount);
        set(12, morningCallRate);
        set(13, createAt);
        set(14, updateAt);
        set(15, delFlag);
        set(16, version);
    }
}
