/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.tables.FdProviderTripInfo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 出行记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdProviderTripInfoRecord extends UpdatableRecordImpl<FdProviderTripInfoRecord> implements Record11<Long, Long, Timestamp, Timestamp, String, String, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = -2023875928;

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.account_id</code>. 账户id
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.account_id</code>. 账户id
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.start_date</code>. 出行开始时间(格式: "YYYY-MM-DD")
     */
    public void setStartDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.start_date</code>. 出行开始时间(格式: "YYYY-MM-DD")
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.end_date</code>. 出行结束时间(格式: "YYYY-MM-DD")
     */
    public void setEndDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.end_date</code>. 出行结束时间(格式: "YYYY-MM-DD")
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.departure</code>. 出发地
     */
    public void setDeparture(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.departure</code>. 出发地
     */
    public String getDeparture() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.destination</code>. 目的地
     */
    public void setDestination(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.destination</code>. 目的地
     */
    public String getDestination() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.time_type</code>. 出行时间类型(节假日/工作日/双休日)
     */
    public void setTimeType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.time_type</code>. 出行时间类型(节假日/工作日/双休日)
     */
    public String getTimeType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>xbkj.fd_provider_trip_info.version</code>.
     */
    public void setVersion(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>xbkj.fd_provider_trip_info.version</code>.
     */
    public Long getVersion() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Long, Timestamp, Timestamp, String, String, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Long, Timestamp, Timestamp, String, String, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.DEPARTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.DESTINATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.TIME_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return FdProviderTripInfo.FD_PROVIDER_TRIP_INFO.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDeparture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDestination();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTimeType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDeparture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDestination();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTimeType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value2(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value3(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value4(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value5(String value) {
        setDeparture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value6(String value) {
        setDestination(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value7(String value) {
        setTimeType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value8(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value9(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value10(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord value11(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdProviderTripInfoRecord values(Long value1, Long value2, Timestamp value3, Timestamp value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9, Boolean value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FdProviderTripInfoRecord
     */
    public FdProviderTripInfoRecord() {
        super(FdProviderTripInfo.FD_PROVIDER_TRIP_INFO);
    }

    /**
     * Create a detached, initialised FdProviderTripInfoRecord
     */
    public FdProviderTripInfoRecord(Long id, Long accountId, Timestamp startDate, Timestamp endDate, String departure, String destination, String timeType, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(FdProviderTripInfo.FD_PROVIDER_TRIP_INFO);

        set(0, id);
        set(1, accountId);
        set(2, startDate);
        set(3, endDate);
        set(4, departure);
        set(5, destination);
        set(6, timeType);
        set(7, createAt);
        set(8, updateAt);
        set(9, delFlag);
        set(10, version);
    }
}
