/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.tables.FdReportFundInfo;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 公积金数据报告基本信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdReportFundInfoRecord extends UpdatableRecordImpl<FdReportFundInfoRecord> {

    private static final long serialVersionUID = 1078029464;

    /**
     * Setter for <code>xbkj.fd_report_fund_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.organization_id</code>.
     */
    public void setOrganizationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.organization_id</code>.
     */
    public Long getOrganizationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.customer_id</code>. 公积金账号
     */
    public void setCustomerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.customer_id</code>. 公积金账号
     */
    public String getCustomerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.organization_type</code>. 机构类型
     */
    public void setOrganizationType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.organization_type</code>. 机构类型
     */
    public String getOrganizationType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.name</code>. 姓名
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.name</code>. 姓名
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.idcard</code>. 身份证号
     */
    public void setIdcard(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.idcard</code>. 身份证号
     */
    public String getIdcard() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.status</code>. 账户状态
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.status</code>. 账户状态
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.company</code>. 当前缴存单位
     */
    public void setCompany(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.company</code>. 当前缴存单位
     */
    public String getCompany() {
        return (String) get(7);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.deposit_rate</code>. 当前缴存比例
     */
    public void setDepositRate(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.deposit_rate</code>. 当前缴存比例
     */
    public BigDecimal getDepositRate() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.deposit_amount</code>. 当前月缴存金额(分)
     */
    public void setDepositAmount(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.deposit_amount</code>. 当前月缴存金额(分)
     */
    public BigDecimal getDepositAmount() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.balance</code>. 当前账户余额(分)
     */
    public void setBalance(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.balance</code>. 当前账户余额(分)
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.last_record_date</code>. 最近一次缴存时间(格式:“YYYY-MM-DD”)
     */
    public void setLastRecordDate(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.last_record_date</code>. 最近一次缴存时间(格式:“YYYY-MM-DD”)
     */
    public String getLastRecordDate() {
        return (String) get(11);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.continuous_deposit_month</code>. 最长连续缴存月份
     */
    public void setContinuousDepositMonth(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.continuous_deposit_month</code>. 最长连续缴存月份
     */
    public String getContinuousDepositMonth() {
        return (String) get(12);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.last_deposit_month</code>. 最近连续缴存月份
     */
    public void setLastDepositMonth(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.last_deposit_month</code>. 最近连续缴存月份
     */
    public String getLastDepositMonth() {
        return (String) get(13);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.loan_count</code>. 公积金贷款笔数
     */
    public void setLoanCount(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.loan_count</code>. 公积金贷款笔数
     */
    public Long getLoanCount() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.loan_repay_amount</code>. 公积金贷款月还款金额(分)
     */
    public void setLoanRepayAmount(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.loan_repay_amount</code>. 公积金贷款月还款金额(分)
     */
    public BigDecimal getLoanRepayAmount() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.monthly_income</code>. 月收入(推断)
     */
    public void setMonthlyIncome(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.monthly_income</code>. 月收入(推断)
     */
    public BigDecimal getMonthlyIncome() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.current_corp_continuous_deposit_month</code>. 当前公司连续缴存月份
     */
    public void setCurrentCorpContinuousDepositMonth(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.current_corp_continuous_deposit_month</code>. 当前公司连续缴存月份
     */
    public String getCurrentCorpContinuousDepositMonth() {
        return (String) get(17);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.corp_type</code>. 缴存单位性质
     */
    public void setCorpType(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.corp_type</code>. 缴存单位性质
     */
    public String getCorpType() {
        return (String) get(18);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.corp_scale</code>. 缴存单位规模
     */
    public void setCorpScale(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.corp_scale</code>. 缴存单位规模
     */
    public String getCorpScale() {
        return (String) get(19);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.user_name</code>. 用户填写姓名
     */
    public void setUserName(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.user_name</code>. 用户填写姓名
     */
    public String getUserName() {
        return (String) get(20);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.user_idcard</code>. 用户填写身份证
     */
    public void setUserIdcard(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.user_idcard</code>. 用户填写身份证
     */
    public String getUserIdcard() {
        return (String) get(21);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.user_phone</code>. 用户填写手机号
     */
    public void setUserPhone(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.user_phone</code>. 用户填写手机号
     */
    public String getUserPhone() {
        return (String) get(22);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.name_match</code>. 姓名是否一致
     */
    public void setNameMatch(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.name_match</code>. 姓名是否一致
     */
    public String getNameMatch() {
        return (String) get(23);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.idcard_match</code>. 身份证是否一致
     */
    public void setIdcardMatch(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.idcard_match</code>. 身份证是否一致
     */
    public String getIdcardMatch() {
        return (String) get(24);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(25, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(25);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(26, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(26);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(27, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(27);
    }

    /**
     * Setter for <code>xbkj.fd_report_fund_info.version</code>.
     */
    public void setVersion(Long value) {
        set(28, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_fund_info.version</code>.
     */
    public Long getVersion() {
        return (Long) get(28);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FdReportFundInfoRecord
     */
    public FdReportFundInfoRecord() {
        super(FdReportFundInfo.FD_REPORT_FUND_INFO);
    }

    /**
     * Create a detached, initialised FdReportFundInfoRecord
     */
    public FdReportFundInfoRecord(Long id, Long organizationId, String customerId, String organizationType, String name, String idcard, String status, String company, BigDecimal depositRate, BigDecimal depositAmount, BigDecimal balance, String lastRecordDate, String continuousDepositMonth, String lastDepositMonth, Long loanCount, BigDecimal loanRepayAmount, BigDecimal monthlyIncome, String currentCorpContinuousDepositMonth, String corpType, String corpScale, String userName, String userIdcard, String userPhone, String nameMatch, String idcardMatch, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(FdReportFundInfo.FD_REPORT_FUND_INFO);

        set(0, id);
        set(1, organizationId);
        set(2, customerId);
        set(3, organizationType);
        set(4, name);
        set(5, idcard);
        set(6, status);
        set(7, company);
        set(8, depositRate);
        set(9, depositAmount);
        set(10, balance);
        set(11, lastRecordDate);
        set(12, continuousDepositMonth);
        set(13, lastDepositMonth);
        set(14, loanCount);
        set(15, loanRepayAmount);
        set(16, monthlyIncome);
        set(17, currentCorpContinuousDepositMonth);
        set(18, corpType);
        set(19, corpScale);
        set(20, userName);
        set(21, userIdcard);
        set(22, userPhone);
        set(23, nameMatch);
        set(24, idcardMatch);
        set(25, createAt);
        set(26, updateAt);
        set(27, delFlag);
        set(28, version);
    }
}
