/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.tables.FdReportEbusinessCards;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 电商数据报告绑卡信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdReportEbusinessCardsRecord extends UpdatableRecordImpl<FdReportEbusinessCardsRecord> implements Record12<Long, Long, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = 1191972267;

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.report_ebusiness_id</code>.
     */
    public void setReportEbusinessId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.report_ebusiness_id</code>.
     */
    public Long getReportEbusinessId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.card</code>. 卡号
     */
    public void setCard(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.card</code>. 卡号
     */
    public String getCard() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.name</code>. 姓名
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.name</code>. 姓名
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.bank</code>. 银行名称
     */
    public void setBank(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.bank</code>. 银行名称
     */
    public String getBank() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.type</code>. 卡类型
     */
    public void setType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.type</code>. 卡类型
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.fast_payment_flag</code>. 是否开通快捷支付
     */
    public void setFastPaymentFlag(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.fast_payment_flag</code>. 是否开通快捷支付
     */
    public String getFastPaymentFlag() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.phone</code>. 手机号
     */
    public void setPhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.phone</code>. 手机号
     */
    public String getPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>xbkj.fd_report_ebusiness_cards.version</code>.
     */
    public void setVersion(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>xbkj.fd_report_ebusiness_cards.version</code>.
     */
    public Long getVersion() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.REPORT_EBUSINESS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.CARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.BANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.FAST_PAYMENT_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getReportEbusinessId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCard();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFastPaymentFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getReportEbusinessId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCard();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFastPaymentFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value2(Long value) {
        setReportEbusinessId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value3(String value) {
        setCard(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value5(String value) {
        setBank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value6(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value7(String value) {
        setFastPaymentFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value8(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value9(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value10(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value11(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord value12(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FdReportEbusinessCardsRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, Timestamp value9, Timestamp value10, Boolean value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FdReportEbusinessCardsRecord
     */
    public FdReportEbusinessCardsRecord() {
        super(FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS);
    }

    /**
     * Create a detached, initialised FdReportEbusinessCardsRecord
     */
    public FdReportEbusinessCardsRecord(Long id, Long reportEbusinessId, String card, String name, String bank, String type, String fastPaymentFlag, String phone, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(FdReportEbusinessCards.FD_REPORT_EBUSINESS_CARDS);

        set(0, id);
        set(1, reportEbusinessId);
        set(2, card);
        set(3, name);
        set(4, bank);
        set(5, type);
        set(6, fastPaymentFlag);
        set(7, phone);
        set(8, createAt);
        set(9, updateAt);
        set(10, delFlag);
        set(11, version);
    }
}
