/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.enums.MsgMessageTemplateMsgType;
import com.jooq.domain.enums.MsgMessageTemplateStatus;
import com.jooq.domain.tables.MsgMessageTemplate;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 消息模板
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MsgMessageTemplateRecord extends UpdatableRecordImpl<MsgMessageTemplateRecord> implements Record13<Long, String, String, MsgMessageTemplateMsgType, String, String, MsgMessageTemplateStatus, String, Boolean, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = -1367501633;

    /**
     * Setter for <code>xbkj.msg_message_template.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.template_name</code>. 模板名称
     */
    public void setTemplateName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.template_name</code>. 模板名称
     */
    public String getTemplateName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.template_code</code>. 模版编码
     */
    public void setTemplateCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.template_code</code>. 模版编码
     */
    public String getTemplateCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.msg_type</code>. 类型：1-短信，2站内信
     */
    public void setMsgType(MsgMessageTemplateMsgType value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.msg_type</code>. 类型：1-短信，2站内信
     */
    public MsgMessageTemplateMsgType getMsgType() {
        return (MsgMessageTemplateMsgType) get(3);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.subject</code>. 标题，简介
     */
    public void setSubject(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.subject</code>. 标题，简介
     */
    public String getSubject() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.content</code>. 模板内容
     */
    public void setContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.content</code>. 模板内容
     */
    public String getContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.status</code>. 状态:等待审核、审核通过、审核未通过
     */
    public void setStatus(MsgMessageTemplateStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.status</code>. 状态:等待审核、审核通过、审核未通过
     */
    public MsgMessageTemplateStatus getStatus() {
        return (MsgMessageTemplateStatus) get(6);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.marketing</code>. 是否是营销短信:0.否 1.是
     */
    public void setMarketing(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.marketing</code>. 是否是营销短信:0.否 1.是
     */
    public Boolean getMarketing() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>xbkj.msg_message_template.version</code>.
     */
    public void setVersion(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>xbkj.msg_message_template.version</code>.
     */
    public Long getVersion() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, MsgMessageTemplateMsgType, String, String, MsgMessageTemplateStatus, String, Boolean, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, MsgMessageTemplateMsgType, String, String, MsgMessageTemplateStatus, String, Boolean, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.TEMPLATE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.TEMPLATE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<MsgMessageTemplateMsgType> field4() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.MSG_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.SUBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<MsgMessageTemplateStatus> field7() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.MARKETING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return MsgMessageTemplate.MSG_MESSAGE_TEMPLATE.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTemplateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTemplateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateMsgType component4() {
        return getMsgType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateStatus component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getMarketing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTemplateName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTemplateCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateMsgType value4() {
        return getMsgType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateStatus value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getMarketing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value2(String value) {
        setTemplateName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value3(String value) {
        setTemplateCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value4(MsgMessageTemplateMsgType value) {
        setMsgType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value5(String value) {
        setSubject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value6(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value7(MsgMessageTemplateStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value9(Boolean value) {
        setMarketing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value10(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value11(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value12(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord value13(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgMessageTemplateRecord values(Long value1, String value2, String value3, MsgMessageTemplateMsgType value4, String value5, String value6, MsgMessageTemplateStatus value7, String value8, Boolean value9, Timestamp value10, Timestamp value11, Boolean value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MsgMessageTemplateRecord
     */
    public MsgMessageTemplateRecord() {
        super(MsgMessageTemplate.MSG_MESSAGE_TEMPLATE);
    }

    /**
     * Create a detached, initialised MsgMessageTemplateRecord
     */
    public MsgMessageTemplateRecord(Long id, String templateName, String templateCode, MsgMessageTemplateMsgType msgType, String subject, String content, MsgMessageTemplateStatus status, String remark, Boolean marketing, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(MsgMessageTemplate.MSG_MESSAGE_TEMPLATE);

        set(0, id);
        set(1, templateName);
        set(2, templateCode);
        set(3, msgType);
        set(4, subject);
        set(5, content);
        set(6, status);
        set(7, remark);
        set(8, marketing);
        set(9, createAt);
        set(10, updateAt);
        set(11, delFlag);
        set(12, version);
    }
}
