/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.tables.OauthCode;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 授权码模式
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthCodeRecord extends UpdatableRecordImpl<OauthCodeRecord> implements Record6<Long, String, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = 714956878;

    /**
     * Setter for <code>xbkj.oauth_code.id</code>. 编号
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.oauth_code.id</code>. 编号
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.oauth_code.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.oauth_code.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xbkj.oauth_code.memeber_id</code>.
     */
    public void setMemeberId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.oauth_code.memeber_id</code>.
     */
    public Long getMemeberId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>xbkj.oauth_code.oauth_client_id</code>.
     */
    public void setOauthClientId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.oauth_code.oauth_client_id</code>.
     */
    public Long getOauthClientId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>xbkj.oauth_code.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.oauth_code.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>xbkj.oauth_code.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.oauth_code.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OauthCode.OAUTH_CODE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OauthCode.OAUTH_CODE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return OauthCode.OAUTH_CODE.MEMEBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return OauthCode.OAUTH_CODE.OAUTH_CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return OauthCode.OAUTH_CODE.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return OauthCode.OAUTH_CODE.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getMemeberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getOauthClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getMemeberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getOauthClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord value3(Long value) {
        setMemeberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord value4(Long value) {
        setOauthClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord value5(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord value6(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthCodeRecord values(Long value1, String value2, Long value3, Long value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OauthCodeRecord
     */
    public OauthCodeRecord() {
        super(OauthCode.OAUTH_CODE);
    }

    /**
     * Create a detached, initialised OauthCodeRecord
     */
    public OauthCodeRecord(Long id, String code, Long memeberId, Long oauthClientId, Timestamp createAt, Timestamp updateAt) {
        super(OauthCode.OAUTH_CODE);

        set(0, id);
        set(1, code);
        set(2, memeberId);
        set(3, oauthClientId);
        set(4, createAt);
        set(5, updateAt);
    }
}
