/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.tables.UcOrganQuality;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 机构资质表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcOrganQualityRecord extends UpdatableRecordImpl<UcOrganQualityRecord> implements Record18<Long, Long, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = -1902827248;

    /**
     * Setter for <code>xbkj.uc_organ_quality.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.organ_id</code>. 机构id
     */
    public void setOrganId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.organ_id</code>. 机构id
     */
    public Long getOrganId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.id_card_front</code>. 身份证正面
     */
    public void setIdCardFront(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.id_card_front</code>. 身份证正面
     */
    public String getIdCardFront() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.id_card_back</code>. 身份证背面
     */
    public void setIdCardBack(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.id_card_back</code>. 身份证背面
     */
    public String getIdCardBack() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.bank_card_front</code>. 银行卡正面
     */
    public void setBankCardFront(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.bank_card_front</code>. 银行卡正面
     */
    public String getBankCardFront() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.bank_card_back</code>. 银行卡背面
     */
    public void setBankCardBack(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.bank_card_back</code>. 银行卡背面
     */
    public String getBankCardBack() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.person_photo</code>. 手持身份证照片
     */
    public void setPersonPhoto(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.person_photo</code>. 手持身份证照片
     */
    public String getPersonPhoto() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.bussiness_license</code>. 营业执照
     */
    public void setBussinessLicense(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.bussiness_license</code>. 营业执照
     */
    public String getBussinessLicense() {
        return (String) get(7);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.bussiness_certificates</code>. 工商证
     */
    public void setBussinessCertificates(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.bussiness_certificates</code>. 工商证
     */
    public String getBussinessCertificates() {
        return (String) get(8);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.organization_code</code>. 组织机构代码证
     */
    public void setOrganizationCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.organization_code</code>. 组织机构代码证
     */
    public String getOrganizationCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.tax_registration</code>. 税务登记证
     */
    public void setTaxRegistration(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.tax_registration</code>. 税务登记证
     */
    public String getTaxRegistration() {
        return (String) get(10);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.inside_img</code>. 店内环境
     */
    public void setInsideImg(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.inside_img</code>. 店内环境
     */
    public String getInsideImg() {
        return (String) get(11);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.front_img</code>. 门前环境
     */
    public void setFrontImg(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.front_img</code>. 门前环境
     */
    public String getFrontImg() {
        return (String) get(12);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.bankaccount_licence</code>. 银行开户许可证
     */
    public void setBankaccountLicence(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.bankaccount_licence</code>. 银行开户许可证
     */
    public String getBankaccountLicence() {
        return (String) get(13);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>xbkj.uc_organ_quality.version</code>.
     */
    public void setVersion(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_quality.version</code>.
     */
    public Long getVersion() {
        return (Long) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UcOrganQuality.UC_ORGAN_QUALITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return UcOrganQuality.UC_ORGAN_QUALITY.ORGAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UcOrganQuality.UC_ORGAN_QUALITY.ID_CARD_FRONT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UcOrganQuality.UC_ORGAN_QUALITY.ID_CARD_BACK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UcOrganQuality.UC_ORGAN_QUALITY.BANK_CARD_FRONT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UcOrganQuality.UC_ORGAN_QUALITY.BANK_CARD_BACK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UcOrganQuality.UC_ORGAN_QUALITY.PERSON_PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UcOrganQuality.UC_ORGAN_QUALITY.BUSSINESS_LICENSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UcOrganQuality.UC_ORGAN_QUALITY.BUSSINESS_CERTIFICATES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return UcOrganQuality.UC_ORGAN_QUALITY.ORGANIZATION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return UcOrganQuality.UC_ORGAN_QUALITY.TAX_REGISTRATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return UcOrganQuality.UC_ORGAN_QUALITY.INSIDE_IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return UcOrganQuality.UC_ORGAN_QUALITY.FRONT_IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return UcOrganQuality.UC_ORGAN_QUALITY.BANKACCOUNT_LICENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return UcOrganQuality.UC_ORGAN_QUALITY.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return UcOrganQuality.UC_ORGAN_QUALITY.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field17() {
        return UcOrganQuality.UC_ORGAN_QUALITY.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return UcOrganQuality.UC_ORGAN_QUALITY.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getOrganId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIdCardFront();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIdCardBack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBankCardFront();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getBankCardBack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPersonPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBussinessLicense();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getBussinessCertificates();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getOrganizationCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getTaxRegistration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getInsideImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getFrontImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getBankaccountLicence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component17() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component18() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOrganId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIdCardFront();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIdCardBack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBankCardFront();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBankCardBack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPersonPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBussinessLicense();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getBussinessCertificates();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getOrganizationCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getTaxRegistration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getInsideImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getFrontImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getBankaccountLicence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value17() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value2(Long value) {
        setOrganId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value3(String value) {
        setIdCardFront(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value4(String value) {
        setIdCardBack(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value5(String value) {
        setBankCardFront(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value6(String value) {
        setBankCardBack(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value7(String value) {
        setPersonPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value8(String value) {
        setBussinessLicense(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value9(String value) {
        setBussinessCertificates(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value10(String value) {
        setOrganizationCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value11(String value) {
        setTaxRegistration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value12(String value) {
        setInsideImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value13(String value) {
        setFrontImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value14(String value) {
        setBankaccountLicence(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value15(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value16(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value17(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord value18(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcOrganQualityRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, Timestamp value15, Timestamp value16, Boolean value17, Long value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UcOrganQualityRecord
     */
    public UcOrganQualityRecord() {
        super(UcOrganQuality.UC_ORGAN_QUALITY);
    }

    /**
     * Create a detached, initialised UcOrganQualityRecord
     */
    public UcOrganQualityRecord(Long id, Long organId, String idCardFront, String idCardBack, String bankCardFront, String bankCardBack, String personPhoto, String bussinessLicense, String bussinessCertificates, String organizationCode, String taxRegistration, String insideImg, String frontImg, String bankaccountLicence, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(UcOrganQuality.UC_ORGAN_QUALITY);

        set(0, id);
        set(1, organId);
        set(2, idCardFront);
        set(3, idCardBack);
        set(4, bankCardFront);
        set(5, bankCardBack);
        set(6, personPhoto);
        set(7, bussinessLicense);
        set(8, bussinessCertificates);
        set(9, organizationCode);
        set(10, taxRegistration);
        set(11, insideImg);
        set(12, frontImg);
        set(13, bankaccountLicence);
        set(14, createAt);
        set(15, updateAt);
        set(16, delFlag);
        set(17, version);
    }
}
