/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.enums.UcOrganShopCooperationType;
import com.jooq.domain.enums.UcOrganShopFeeType;
import com.jooq.domain.enums.UcOrganShopItsOrganShop;
import com.jooq.domain.enums.UcOrganShopStatus;
import com.jooq.domain.tables.UcOrganShop;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 门店表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcOrganShopRecord extends UpdatableRecordImpl<UcOrganShopRecord> {

    private static final long serialVersionUID = 1585723315;

    /**
     * Setter for <code>xbkj.uc_organ_shop.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.organ_id</code>. 机构id
     */
    public void setOrganId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.organ_id</code>. 机构id
     */
    public Long getOrganId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.yeepay_id</code>. 易宝id
     */
    public void setYeepayId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.yeepay_id</code>. 易宝id
     */
    public String getYeepayId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.name</code>. 门店名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.name</code>. 门店名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.organ_name</code>. 机构名称
     */
    public void setOrganName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.organ_name</code>. 机构名称
     */
    public String getOrganName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.attribute</code>. 属性
     */
    public void setAttribute(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.attribute</code>. 属性
     */
    public String getAttribute() {
        return (String) get(5);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.no</code>. 编号
     */
    public void setNo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.no</code>. 编号
     */
    public String getNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.popularity</code>. 人气
     */
    public void setPopularity(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.popularity</code>. 人气
     */
    public Integer getPopularity() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.province</code>. 省份
     */
    public void setProvince(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.province</code>. 省份
     */
    public String getProvince() {
        return (String) get(8);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.city</code>. 城市
     */
    public void setCity(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.city</code>. 城市
     */
    public String getCity() {
        return (String) get(9);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.area</code>. 地区
     */
    public void setArea(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.area</code>. 地区
     */
    public String getArea() {
        return (String) get(10);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.logo_url</code>. logo地址
     */
    public void setLogoUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.logo_url</code>. logo地址
     */
    public String getLogoUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.position</code>. 经纬度（英文逗号分割）(latutude,longitude)纬度，经度
     */
    public void setPosition(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.position</code>. 经纬度（英文逗号分割）(latutude,longitude)纬度，经度
     */
    public String getPosition() {
        return (String) get(12);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.longitude</code>. 经度
     */
    public void setLongitude(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.longitude</code>. 经度
     */
    public Double getLongitude() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.dimension</code>. 维度
     */
    public void setDimension(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.dimension</code>. 维度
     */
    public Double getDimension() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.address</code>. 地址
     */
    public void setAddress(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.address</code>. 地址
     */
    public String getAddress() {
        return (String) get(15);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.telephone</code>. 电话
     */
    public void setTelephone(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.telephone</code>. 电话
     */
    public String getTelephone() {
        return (String) get(16);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.age_start</code>. 适合年龄段开始
     */
    public void setAgeStart(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.age_start</code>. 适合年龄段开始
     */
    public Integer getAgeStart() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.age_end</code>. 适合年龄段结束
     */
    public void setAgeEnd(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.age_end</code>. 适合年龄段结束
     */
    public Integer getAgeEnd() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.status</code>. 状态：保存，审核中，正常，禁用，其他，审核失败，提交中，待上线
     */
    public void setStatus(UcOrganShopStatus value) {
        set(19, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.status</code>. 状态：保存，审核中，正常，禁用，其他，审核失败，提交中，待上线
     */
    public UcOrganShopStatus getStatus() {
        return (UcOrganShopStatus) get(19);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.join_date</code>. 加入日期
     */
    public void setJoinDate(Timestamp value) {
        set(20, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.join_date</code>. 加入日期
     */
    public Timestamp getJoinDate() {
        return (Timestamp) get(20);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.maintainer</code>. 维护人员
     */
    public void setMaintainer(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.maintainer</code>. 维护人员
     */
    public String getMaintainer() {
        return (String) get(21);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.maintainer_id</code>. 维护人员id
     */
    public void setMaintainerId(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.maintainer_id</code>. 维护人员id
     */
    public Long getMaintainerId() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.intro</code>. 简介
     */
    public void setIntro(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.intro</code>. 简介
     */
    public String getIntro() {
        return (String) get(23);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.detail_intro</code>. 详细介绍
     */
    public void setDetailIntro(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.detail_intro</code>. 详细介绍
     */
    public String getDetailIntro() {
        return (String) get(24);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.qrcode</code>. 二维码
     */
    public void setQrcode(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.qrcode</code>. 二维码
     */
    public String getQrcode() {
        return (String) get(25);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.is_open_payment</code>. 是否开通门店支付
     */
    public void setIsOpenPayment(Boolean value) {
        set(26, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.is_open_payment</code>. 是否开通门店支付
     */
    public Boolean getIsOpenPayment() {
        return (Boolean) get(26);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.is_add_bankaccount</code>. 是否添加账户
     */
    public void setIsAddBankaccount(Boolean value) {
        set(27, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.is_add_bankaccount</code>. 是否添加账户
     */
    public Boolean getIsAddBankaccount() {
        return (Boolean) get(27);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.deal_count</code>. 累计交易规模
     */
    public void setDealCount(BigDecimal value) {
        set(28, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.deal_count</code>. 累计交易规模
     */
    public BigDecimal getDealCount() {
        return (BigDecimal) get(28);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.credit_count</code>. 信用分期规模
     */
    public void setCreditCount(BigDecimal value) {
        set(29, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.credit_count</code>. 信用分期规模
     */
    public BigDecimal getCreditCount() {
        return (BigDecimal) get(29);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.users_count</code>. 累计用户数
     */
    public void setUsersCount(Long value) {
        set(30, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.users_count</code>. 累计用户数
     */
    public Long getUsersCount() {
        return (Long) get(30);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.cooperation_type</code>. 合作方式：CPA，CPS
     */
    public void setCooperationType(UcOrganShopCooperationType value) {
        set(31, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.cooperation_type</code>. 合作方式：CPA，CPS
     */
    public UcOrganShopCooperationType getCooperationType() {
        return (UcOrganShopCooperationType) get(31);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.cooperation_income</code>. 合作收益，20%，=0.2
     */
    public void setCooperationIncome(BigDecimal value) {
        set(32, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.cooperation_income</code>. 合作收益，20%，=0.2
     */
    public BigDecimal getCooperationIncome() {
        return (BigDecimal) get(32);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.fee_type</code>. 手续费收取 方式 默认商户承担
     */
    public void setFeeType(UcOrganShopFeeType value) {
        set(33, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.fee_type</code>. 手续费收取 方式 默认商户承担
     */
    public UcOrganShopFeeType getFeeType() {
        return (UcOrganShopFeeType) get(33);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.its_organ_shop</code>. 是否使用机构账号
     */
    public void setItsOrganShop(UcOrganShopItsOrganShop value) {
        set(34, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.its_organ_shop</code>. 是否使用机构账号
     */
    public UcOrganShopItsOrganShop getItsOrganShop() {
        return (UcOrganShopItsOrganShop) get(34);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.event_record</code>. 调用易宝错误返回信息
     */
    public void setEventRecord(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.event_record</code>. 调用易宝错误返回信息
     */
    public String getEventRecord() {
        return (String) get(35);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(36, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(36);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(37, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(37);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(38, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(38);
    }

    /**
     * Setter for <code>xbkj.uc_organ_shop.version</code>.
     */
    public void setVersion(Long value) {
        set(39, value);
    }

    /**
     * Getter for <code>xbkj.uc_organ_shop.version</code>.
     */
    public Long getVersion() {
        return (Long) get(39);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UcOrganShopRecord
     */
    public UcOrganShopRecord() {
        super(UcOrganShop.UC_ORGAN_SHOP);
    }

    /**
     * Create a detached, initialised UcOrganShopRecord
     */
    public UcOrganShopRecord(Long id, Long organId, String yeepayId, String name, String organName, String attribute, String no, Integer popularity, String province, String city, String area, String logoUrl, String position, Double longitude, Double dimension, String address, String telephone, Integer ageStart, Integer ageEnd, UcOrganShopStatus status, Timestamp joinDate, String maintainer, Long maintainerId, String intro, String detailIntro, String qrcode, Boolean isOpenPayment, Boolean isAddBankaccount, BigDecimal dealCount, BigDecimal creditCount, Long usersCount, UcOrganShopCooperationType cooperationType, BigDecimal cooperationIncome, UcOrganShopFeeType feeType, UcOrganShopItsOrganShop itsOrganShop, String eventRecord, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(UcOrganShop.UC_ORGAN_SHOP);

        set(0, id);
        set(1, organId);
        set(2, yeepayId);
        set(3, name);
        set(4, organName);
        set(5, attribute);
        set(6, no);
        set(7, popularity);
        set(8, province);
        set(9, city);
        set(10, area);
        set(11, logoUrl);
        set(12, position);
        set(13, longitude);
        set(14, dimension);
        set(15, address);
        set(16, telephone);
        set(17, ageStart);
        set(18, ageEnd);
        set(19, status);
        set(20, joinDate);
        set(21, maintainer);
        set(22, maintainerId);
        set(23, intro);
        set(24, detailIntro);
        set(25, qrcode);
        set(26, isOpenPayment);
        set(27, isAddBankaccount);
        set(28, dealCount);
        set(29, creditCount);
        set(30, usersCount);
        set(31, cooperationType);
        set(32, cooperationIncome);
        set(33, feeType);
        set(34, itsOrganShop);
        set(35, eventRecord);
        set(36, createAt);
        set(37, updateAt);
        set(38, delFlag);
        set(39, version);
    }
}
