/*
 * This file is generated by jOOQ.
*/
package com.jooq.domain.tables.records;


import com.jooq.domain.enums.UcTagType;
import com.jooq.domain.tables.UcTag;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 标签表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UcTagRecord extends UpdatableRecordImpl<UcTagRecord> implements Record7<Long, UcTagType, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = -1778925193;

    /**
     * Setter for <code>xbkj.uc_tag.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>xbkj.uc_tag.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>xbkj.uc_tag.type</code>. 类型：机构，门店，课程
     */
    public void setType(UcTagType value) {
        set(1, value);
    }

    /**
     * Getter for <code>xbkj.uc_tag.type</code>. 类型：机构，门店，课程
     */
    public UcTagType getType() {
        return (UcTagType) get(1);
    }

    /**
     * Setter for <code>xbkj.uc_tag.name</code>. 标签
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xbkj.uc_tag.name</code>. 标签
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xbkj.uc_tag.create_at</code>. 创建时间
     */
    public void setCreateAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>xbkj.uc_tag.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>xbkj.uc_tag.update_at</code>. 更新时间
     */
    public void setUpdateAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>xbkj.uc_tag.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>xbkj.uc_tag.del_flag</code>. 删除标志
     */
    public void setDelFlag(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>xbkj.uc_tag.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>xbkj.uc_tag.version</code>.
     */
    public void setVersion(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>xbkj.uc_tag.version</code>.
     */
    public Long getVersion() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, UcTagType, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, UcTagType, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UcTag.UC_TAG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UcTagType> field2() {
        return UcTag.UC_TAG.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UcTag.UC_TAG.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return UcTag.UC_TAG.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UcTag.UC_TAG.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return UcTag.UC_TAG.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return UcTag.UC_TAG.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagType component2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagType value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagRecord value2(UcTagType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagRecord value4(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagRecord value5(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagRecord value6(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagRecord value7(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UcTagRecord values(Long value1, UcTagType value2, String value3, Timestamp value4, Timestamp value5, Boolean value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UcTagRecord
     */
    public UcTagRecord() {
        super(UcTag.UC_TAG);
    }

    /**
     * Create a detached, initialised UcTagRecord
     */
    public UcTagRecord(Long id, UcTagType type, String name, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(UcTag.UC_TAG);

        set(0, id);
        set(1, type);
        set(2, name);
        set(3, createAt);
        set(4, updateAt);
        set(5, delFlag);
        set(6, version);
    }
}
